# This config file is deployed with the static site because Circle CI also runs on the gh-pages branch
# but we don't want it to show a red CI status.

version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:11.12.0
    steps:
      - run:
          name: Dummy
          command: 'echo Not running any CI on static site'
